USE lostfoundsystem;

INSERT INTO `governments` (`id`, `name`) VALUES
(1, 'Cairo'),
(2, 'Giza'),
(3, 'Alexandria'),
(4, 'Dakahlia'),
(5, 'Red Sea'),
(6, 'Beheira'),
(7, 'Fayoum'),
(8, 'Gharbiya'),
(9, 'Ismailia'),
(10, 'Menofia'),
(11, 'Minya'),
(12, 'Qaliubiya'),
(13, 'New Valley'),
(14, 'Suez'),
(15, 'Aswan'),
(16, 'Assiut'),
(17, 'Beni Suef'),
(18, 'Port Said'),
(19, 'Damietta'),
(20, 'Sharkia'),
(21, 'South Sinai'),
(22, 'Kafr Al sheikh'),
(23, 'Matrouh'),
(24, 'Luxor'),
(25, 'Qena'),
(26, 'North Sinai'),
(27, 'Sohag');




INSERT INTO `cities` (`government_id`, `name`) VALUES

/* Start Cairo ID:1 */
(1, '15 May'),
(1, 'Al Azbakeyah'),
(1, 'Al Basatin'),
(1, 'Tebin'),
(1, 'El-Khalifa'),
(1, 'El darrasa'),
(1, 'Aldarb Alahmar'),
(1, 'Zawya al-Hamra'),
(1, 'El-Zaytoun'),
(1, 'Sahel'),
(1, 'El Salam'),
(1, 'Sayeda Zeinab'),
(1, 'El Sharabeya'),
(1, 'Shorouk'),
(1, 'El Daher'),
(1, 'Ataba'),
(1, 'New Cairo'),
(1, 'El Marg'),
(1, 'Ezbet el Nakhl'),
(1, 'Matareya'),
(1, 'Maadi'),
(1, 'Maasara'),
(1, 'Mokattam'),
(1, 'Manyal'),
(1, 'Mosky'),
(1, 'Nozha'),
(1, 'Waily'),
(1, 'Bab al-Shereia'),
(1, 'Bolaq'),
(1, 'Garden City'),
(1, 'Hadayek El-Kobba'),
(1, 'Helwan'),
(1, 'Dar Al Salam'),
(1, 'Shubra'),
(1, 'Tura'),
(1, 'Abdeen'),
(1, 'Abaseya'),
(1, 'Ain Shams'),
(1, 'Nasr City'),
(1, 'New Heliopolis'),
(1, 'Masr Al Qadima'),
(1, 'Mansheya Nasir'),
(1, 'Badr City'),
(1, 'Obour City'),
(1, 'Cairo Downtown'),
(1, 'Zamalek'),
(1, 'Kasr El Nile'),
(1, 'Rehab'),
(1, 'Katameya'),
(1, 'Madinty'),
(1, 'Rod Alfarag'),
(1, 'Sheraton'),
(1, 'El-Gamaleya'),
(1, '10th of Ramadan City'),
(1, 'Helmeyat Alzaytoun'),
(1, 'New Nozha'),
(1, 'Capital New'),
/* End Cairo ID:1 */

/* Start Giza ID:2 */
(2, 'Giza'),
(2, 'Sixth of October'),
(2, 'Cheikh Zayed'),
(2, 'Hawamdiyah'),
(2, 'Al Badrasheen'),
(2, 'Saf'),
(2, 'Atfih'),
(2, 'Al Ayat'),
(2, 'Al-Bawaiti'),
(2, 'ManshiyetAl Qanater'),
(2, 'Oaseem'),
(2, 'Kerdasa'),
(2, 'Abu Nomros'),
(2, 'Kafr Ghati'),
(2, 'Manshiyet Al Bakari'),
(2, 'Dokki'),
(2, 'Agouza'),
(2, 'Haram'),
(2, 'Warraq'),
(2, 'Imbaba'),
(2, 'Boulaq Dakrour'),
(2, 'Al Wahat Al Baharia'),
(2, 'Omraneya'),
(2, 'Moneeb'),
(2, 'Bin Alsarayat'),
(2, 'Kit Kat'),
(2, 'Mohandessin'),
(2, 'Faisal'),
(2, 'Abu Rawash'),
(2, 'Hadayek Alahram'),
(2, 'Haraneya'),
(2, 'Hadayek October'),
(2, 'Saft Allaban'),
(2, 'Smart Village'),
(2, 'Ard Ellwaa'),
/* End Giza ID:2 */

/* Start Alexandria ID:3 */
(3, 'Abu Qir'),
(3, 'Al Ibrahimeyah'),
(3, 'Azarita'),
(3, 'Anfoushi'),
(3, 'Dekheila'),
(3, 'El Soyof'),
(3, 'Ameria'),
(3, 'El Labban'),
(3, 'Al Mafrouza'),
(3, 'El Montaza'),
(3, 'Mansheya'),
(3, 'Naseria'),
(3, 'Ambrozo'),
(3, 'Bab Sharq'),
(3, 'Bourj Alarab'),
(3, 'Stanley'),
(3, 'Smouha'),
(3, 'Sidi Bishr'),
(3, 'Shads'),
(3, 'Gheet Alenab'),
(3, 'Fleming'),
(3, 'Victoria'),
(3, 'Camp Shizar'),
(3, 'Karmooz'),
(3, 'Mahta Alraml'),
(3, 'Mina El-Basal'),
(3, 'Asafra'),
(3, 'Agamy'),
(3, 'Bakos'),
(3, 'Boulkly'),
(3, 'Cleopatra'),
(3, 'Glim'),
(3, 'Al Mamurah'),
(3, 'Al Mandara'),
(3, 'Moharam Bek'),
(3, 'Elshatby'),
(3, 'Sidi Gaber'),
(3, 'North Coast/sahel'),
(3, 'Alhadra'),
(3, 'Alattarin'),
(3, 'Sidi Kerir'),
(3, 'Elgomrok'),
(3, 'Al Max'),
(3, 'Marina'),
/* End Alexandria ID:3 */

/* Start Dakahlia ID:4 */
(4, 'Mansoura'),
(4, 'Talkha'),
(4, 'Mitt Ghamr'),
(4, 'Dekernes'),
(4, 'Aga'),
(4, 'Menia El Nasr'),
(4, 'Sinbillawin'),
(4, 'El Kurdi'),
(4, 'Bani Ubaid'),
(4, 'Al Manzala'),
(4, 'tami alamdid'),
(4, 'aljamalia'),
(4, 'Sherbin'),
(4, 'Mataria'),
(4, 'Belqas'),
(4, 'Meet Salsil'),
(4, 'Gamasa'),
(4, 'Mahalat Damana'),
(4, 'Nabroh'),
/* End Dakahlia ID:4 */

/* Start Red Sea ID:5 */
(5, 'Hurghada'),
(5, 'Ras Ghareb'),
(5, 'Safaga'),
(5, 'El Qusiar'),
(5, 'Marsa Alam'),
(5, 'Shalatin'),
(5, 'Halaib'),
(5, 'Aldahar'),
/* End Red Sea ID:5 */

/* Start Beheira ID:6 */
(6, 'Damanhour'),
(6, 'Kafr El Dawar'),
(6, 'Rashid'),
(6, 'Edco'),
(6, 'Abu al-Matamir'),
(6, 'Abu Homs'),
(6, 'Delengat'),
(6, 'Mahmoudiyah'),
(6, 'Rahmaniyah'),
(6, 'Itai Baroud'),
(6, 'Housh Eissa'),
(6, 'Shubrakhit'),
(6, 'Kom Hamada'),
(6, 'Badr'),
(6, 'Wadi Natrun'),
(6, 'New Nubaria'),
(6, 'Alnoubareya'),
/* End Beheira ID:6 */

/* Start Fayoum ID:7 */
(7, 'Fayoum'),
(7, 'Fayoum El Gedida'),
(7, 'Tamiya'),
(7, 'Snores'),
(7, 'Etsa'),
(7, 'Epschway'),
(7, 'Yusuf El Sediaq'),
(7, 'Hadqa'),
(7, 'Atsa'),
(7, 'Algamaa'),
(7, 'Sayala'),
/* End Fayoum ID:7 */

/* Start Gharbia ID:8 */
(8, 'Tanta'),
(8, 'Al Mahalla Al Kobra'),
(8, 'Kafr El Zayat'),
(8, 'Zefta'),
(8, 'El Santa'),
(8, 'Qutour'),
(8, 'Basion'),
(8, 'Samannoud'),
/* End Gharbia ID:8 */

/* Start Ismailia ID:9 */
(9, 'Ismailia'),
(9, 'Fayed'),
(9, 'Qantara Sharq'),
(9, 'Qantara Gharb'),
(9, 'El Tal El Kabier'),
(9, 'Abu Sawir'),
(9, 'Kasasien El Gedida'),
(9, 'Nefesha'),
(9, 'Sheikh Zayed'),
/* End Ismailia ID:9 */

/* Start Monufya ID:10 */
(10, 'Shbeen El Koom'),
(10, 'Sadat City'),
(10, 'Menouf'),
(10, 'Sars El-Layan'),
(10, 'Ashmon'),
(10, 'Al Bagor'),
(10, 'Quesna'),
(10, 'Berkat El Saba'),
(10, 'Tala'),
(10, 'Al Shohada'),
/* Start Monufya ID:10 */

/* Start Minya ID:11 */
(11, 'Minya'),
(11, 'Minya El Gedida'),
(11, 'El Adwa'),
(11, 'Magagha'),
(11, 'Bani Mazar'),
(11, 'Mattay'),
(11, 'Samalut'),
(11, 'Madinat El Fekria'),
(11, 'Meloy'),
(11, 'Deir Mawas'),
(11, 'Abu Qurqas'),
(11, 'Ard Sultan'),
/* End Minya ID:11 */

/* Start Qalubia ID:12 */
(12, 'Banha'),
(12, 'Qalyub'),
(12, 'Shubra Al Khaimah'),
(12, 'Al Qanater Charity'),
(12, 'Khanka'),
(12, 'Kafr Shukr'),
(12, 'Tukh'),
(12, 'Qaha'),
(12, 'Obour'),
(12, 'Khosous'),
(12, 'Shibin Al Qanater'),
(12, 'Mostorod'),
/* End Qalubia ID:12 */

/* Start New Valley ID:13 */
(13, 'El Kharga'),
(13, 'Paris'),
(13, 'Mout'),
(13, 'Farafra'),
(13, 'Balat'),
(13, 'Dakhla'),
/* End New Valley ID:13 */

/* Start South Sinai ID:14 */
(14, 'Suez'),
(14, 'Alganayen'),
(14, 'Ataqah'),
(14, 'Ain Sokhna'),
(14, 'Faysal'),
/* End South Sinai ID:14 */

/* Start Aswan ID:15 */
(15, 'Aswan'),
(15, 'Aswan El Gedida'),
(15, 'Drau'),
(15, 'Kom Ombo'),
(15, 'Nasr Al Nuba'),
(15, 'Kalabsha'),
(15, 'Edfu'),
(15, 'Al-Radisiyah'),
(15, 'Al Basilia'),
(15, 'Al Sibaeia'),
(15, 'Abo Simbl Al Siyahia'),
(15, 'Marsa Alam'),
/* End Aswan ID:15 */

/* Start Assiut ID:16 */
(16, 'Assiut'),
(16, 'Assiut El Gedida'),
(16, 'Dayrout'),
(16, 'Manfalut'),
(16, 'Qusiya'),
(16, 'Abnoub'),
(16, 'Abu Tig'),
(16, 'El Ghanaim'),
(16, 'Sahel Selim'),
(16, 'El Badari'),
(16, 'Sidfa'),
/* End Assiut ID:16 */

/* Start Bani Sweif ID:17 */
(17, 'Bani Sweif'),
(17, 'Beni Suef El Gedida'),
(17, 'Al Wasta'),
(17, 'Naser'),
(17, 'Ehnasia'),
(17, 'beba'),
(17, 'Fashn'),
(17, 'Somasta'),
(17, 'Alabbaseri'),
(17, 'Mokbel'),
/* End Bani Sweif ID:17 */

/* Start PorSaid ID:18 */
(18, 'PorSaid'),
(18, 'Port Fouad'),
(18, 'Alarab'),
(18, 'Zohour'),
(18, 'Alsharq'),
(18, 'Aldawahi'),
(18, 'Almanakh'),
(18, 'Mubarak'),
/* End PorSaid ID:18 */

/* Start Damietta ID:19 */
(19, 'Damietta'),
(19, 'New Damietta'),
(19, 'Ras El Bar'),
(19, 'Faraskour'),
(19, 'Zarqa'),
(19, 'alsaru'),
(19, 'alruwda'),
(19, 'Kafr El-Batikh'),
(19, 'Azbet Al Burg'),
(19, 'Meet Abou Ghalib'),
(19, 'Kafr Saad'),
/* End Damietta ID:19 */

/* Start Sharqia ID:20 */
(20, 'Zagazig'),
(20, 'Al Ashr Men Ramadan'),
(20, 'Minya Al Qamh'),
(20, 'Belbeis'),
(20, 'Mashtoul El Souq'),
(20, 'Qenaiat'),
(20, 'Abu Hammad'),
(20, 'El Qurain'),
(20, 'Hehia'),
(20, 'Abu Kabir'),
(20, 'Faccus'),
(20, 'El Salihia El Gedida'),
(20, 'Al Ibrahimiyah'),
(20, 'Deirb Negm'),
(20, 'Kafr Saqr'),
(20, 'Awlad Saqr'),
(20, 'Husseiniya'),
(20, 'san alhajar alqablia'),
(20, 'Manshayat Abu Omar'),
/* End Sharqia ID:20 */

/* Start South Sinai ID:21 */
(21, 'Al Toor'),
(21, 'Sharm El-Shaikh'),
(21, 'Dahab'),
(21, 'Nuweiba'),
(21, 'Taba'),
(21, 'Saint Catherine'),
(21, 'Abu Redis'),
(21, 'Abu Zenaima'),
(21, 'Ras Sidr'),
/* End South Sinai ID:21 */

/* Start Kafr El Sheikh ID:22 */
(22, 'Kafr El Sheikh'),
(22, 'Kafr El Sheikh Downtown'),
(22, 'Desouq'),
(22, 'Fooh'),
(22, 'Metobas'),
(22, 'Burg Al Burullus'),
(22, 'Baltim'),
(22, 'Masief Baltim'),
(22, 'Hamol'),
(22, 'Bella'),
(22, 'Riyadh'),
(22, 'Sidi Salm'),
(22, 'Qellen'),
(22, 'Sidi Ghazi'),
/* End Kafr El Sheikh ID:22 */

/* Start Matrouh ID:23 */
(23, 'Marsa Matrouh'),
(23, 'El Hamam'),
(23, 'Alamein'),
(23, 'Dabaa'),
(23, 'Al-Nagila'),
(23, 'Sidi Brani'),
(23, 'Salloum'),
(23, 'Siwa'),
(23, 'Marina'),
(23, 'North Coast'),
/* End Matrouh ID:23 */

/* Start Luxor ID:24 */
(24, 'Luxor'),
(24, 'New Luxor'),
(24, 'Esna'),
(24, 'New Tiba'),
(24, 'Al ziynia'),
(24, 'Al Bayadieh'),
(24, 'Al Qarna'),
(24, 'Armant'),
(24, 'Al Tud'),
/* End Luxor ID:24 */

/* Start Qena ID:25 */
(25, 'Qena'),
(25, 'New Qena'),
(25, 'Abu Tesht'),
(25, 'Nag Hammadi'),
(25, 'Deshna'),
(25, 'Alwaqf'),
(25, 'Qaft'),
(25, 'Naqada'),
(25, 'Farshout'),
(25, 'Quos'),
/* End Qena ID:25 */

/* Start North Sinai ID:26 */
(26, 'Arish'),
(26, 'Sheikh Zowaid'),
(26, 'Nakhl'),
(26, 'Rafah'),
(26, 'Bir al-Abed'),
(26, 'Al Hasana'),
/* End North Sinai ID:26 */

/* Start Sohag ID:27 */
(27, 'Sohag'),
(27, 'Sohag El Gedida'),
(27, 'Akhmeem'),
(27, 'Akhmim El Gedida'),
(27, 'Albalina'),
(27, 'El Maragha'),
(27, 'almunshaa'),
(27, 'Dar AISalaam'),
(27, 'Gerga'),
(27, 'Jahina Al Gharbia'),
(27, 'Saqilatuh'),
(27, 'Tama'),
(27, 'Tahta'),
(27, 'Alkawthar');
/* End Sharqia ID:27 */
