'use strict';

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Items',
      [
        {
          title: 'Lost Wallet',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-03-14',
          type: 'lost',
          description: 'Black leather wallet with several cards',
          user_id: 1,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Mobile Phone',
          government: 'Cairo',
          city: 'El Shorouk',
          place: 'street',
          date: '2025-05-09',
          type: 'found',
          description: 'Samsung phone found near the beach',
          user_id: 2,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Backpack',
          government: 'Giza',
          city: 'Pyramids',
          place: 'public_transport',
          date: '2025-02-01',
          type: 'lost',
          description: 'Blue backpack with laptop inside',
          user_id: 3,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Keys',
          government: 'Giza',
          city: 'Dokki',
          place: 'school',
          date: '2026-01-08',
          type: 'found',
          description: 'House keys with red keychain',
          user_id: 4,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Watch',
          government: 'Giza',
          city: 'Agouza',
          place: 'university',
          date: '2023-12-05',
          type: 'lost',
          description: 'Silver wrist watch, brand unknown',
          user_id: 5,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Headphones',
          government: 'Gharbia',
          city: 'Tanta',
          place: 'mall',
          date: '2024-09-14',
          type: 'found',
          description: 'Wireless black headphones',
          user_id: 1,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost ID Card',
          government: 'Gharbia',
          city: 'Zifta',
          place: 'restaurant',
          date: '2025-9-20',
          type: 'lost',
          description: 'National ID card issued in Gharbia',
          user_id: 2,
          item_category_id: 6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Sunglasses',
          government: 'Gharbia',
          city: 'Samanoud',
          place: 'hospital',
          date: '2025-5-03',
          type: 'found',
          description: 'Brown sunglasses found in a cafe',
          user_id: 3,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Jacket',
          government: 'Kafr-Elsheikh',
          city: 'Desouk',
          place: 'bank',
          date: '2025-12-31',
          type: 'lost',
          description: 'Black winter jacket size L',
          user_id: 4,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Power Bank',
          government: 'Kafr-Elsheikh',
          city: 'Qallin',
          place: 'office',
          date: '2025-08-08',
          type: 'found',
          description: 'White power bank, 20000mAh',
          user_id: 5,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Wallet',
          government: 'Kafr-Elsheikh',
          city: 'Sidi Salem',
          place: 'gym',
          date: '2025-01-10',
          type: 'lost',
          description: 'Brown leather wallet with multiple cards and some cash',
          user_id: 6,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Backpack',
          government: 'Sharqia',
          city: 'El Qurein',
          place: 'park',
          date: '2025-02-05',
          type: 'found',
          description: 'Grey backpack with school books inside',
          user_id: 7,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Mobile Phone',
          government: 'Sharqia',
          city: 'Awlad Saqr',
          place: 'cinema',
          date: '2026-01-08',
          type: 'lost',
          description: 'iPhone 13, black color, no case',
          user_id: 8,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Wallet',
          government: 'Sharqia',
          city: 'Zagazig',
          place: 'theater',
          date: '2024-11-08',
          type: 'found',
          description: 'Black wallet with a few cards, no cash',
          user_id: 9,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Keys',
          government: 'Alexandria',
          city: 'El Manshiyya',
          place: 'bus_station',
          date: '2023-01-22',
          type: 'lost',
          description: 'House keys with blue keychain',
          user_id: 10,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Watch',
          government: 'Alexandria',
          city: 'Karmouz',
          place: 'metro_station',
          date: '2024-12-23',
          type: 'found',
          description: 'Silver wrist watch with leather strap',
          user_id: 6,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Headphones',
          government: 'Alexandria',
          city: 'Sidi Gaber',
          place: 'metro_station',
          date: '2025-01-05',
          type: 'lost',
          description: 'Wireless black headphones with noise cancellation',
          user_id: 7,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found ID Card',
          government: 'Aswan',
          city: 'Abu Simbel',
          place: 'metro_station',
          date: '2025-02-11',
          type: 'found',
          description: 'National ID card issued in Aswan',
          user_id: 8,
          item_category_id: 6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Sunglasses',
          government: 'Aswan',
          city: 'Edfu',
          place: 'train_station',
          date: '2026-01-26',
          type: 'lost',
          description: 'Brown aviator sunglasses with metal frame',
          user_id: 9,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Jacket',
          government: 'Aswan',
          city: 'Nasr',
          place: 'train_station',
          date: '2022-02-08',
          type: 'found',
          description: 'Black winter jacket size M, lightly worn',
          user_id: 10,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Power Bank',
          government: 'Asyut',
          city: 'Dairut',
          place: 'train_station',
          date: '2025-07-08',
          type: 'lost',
          description: 'White power bank, 20000mAh capacity',
          user_id: 6,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Backpack',
          government: 'Asyut',
          city: 'Manfalut',
          place: 'airport',
          date: '2025-07-26',
          type: 'found',
          description: 'Red backpack with school notebooks',
          user_id: 7,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Wallet',
          government: 'Asyut',
          city: 'Sidfa',
          place: 'airport',
          date: '2025-07-29',
          type: 'lost',
          description: 'Small black wallet with coins and a few credit cards',
          user_id: 8,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Mobile Phone',
          government: 'Asyut',
          city: 'Sahel Selim',
          place: 'taxi',
          date: '2025-05-30',
          type: 'found',
          description: 'Samsung Galaxy A12, black color',
          user_id: 9,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Keys',
          government: 'Beheira',
          city: 'Abu El Matamir',
          place: 'taxi',
          date: '2025-02-28',
          type: 'lost',
          description: 'Car keys with a red keychain and remote',
          user_id: 10,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Watch',
          government: 'Beheira',
          city: 'Abu Hummus',
          place: 'taxi',
          date: '2025-04-01',
          type: 'found',
          description: 'Gold-colored wrist watch, brand unknown',
          user_id: 6,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Headphones',
          government: 'Beheira',
          city: 'ShoEl Delengatbra',
          place: 'supermarket',
          date: '2025-07-01',
          type: 'lost',
          description: 'Over-ear black headphones, wireless',
          user_id: 7,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Sunglasses',
          government: 'Beni Suef',
          city: 'El Fashn',
          place: 'supermarket',
          date: '2025-09-25',
          type: 'found',
          description: 'Round brown sunglasses, lightly scratched',
          user_id: 8,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Jacket',
          government: 'Beni Suef',
          city: 'Nasser',
          place: 'supermarket',
          date: '2025-06-02',
          type: 'lost',
          description: 'Blue denim jacket, size L',
          user_id: 9,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Power Bank',
          government: 'Beni Suef',
          city: 'Sumusta El Waqf',
          place: 'stadium',
          date: '2025-01-01',
          type: 'found',
          description: 'Black power bank, 10000mAh',
          user_id: 10,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        }      
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Items', null, {});
  },
};
