'use strict';

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Messages',
      [
{
    sender_id: 1,
    receiver_id: 2,
    item_id: 1,
    content: 'Hi, I think I might have seen your lost wallet near Tahrir Square earlier today. It looked just like the picture you uploaded, so I picked it up for you.',
    sent_at: new Date(),
  },
  {
    sender_id: 2,
    receiver_id: 1,
    item_id: 1,
    content: 'Oh wow, really? Thank you so much! Where can we meet so I can collect it from you?',
    sent_at: new Date(),
  },
  {
    sender_id: 3,
    receiver_id: 4,
    item_id: 2,
    content: 'I found a phone that might belong to you. The color and model match what you described in your post. I can drop it off at a safe place for you.',
    sent_at: new Date(),
  },
  {
    sender_id: 4,
    receiver_id: 3,
    item_id: 2,
    content: 'That’s perfect! I appreciate it. I can meet you at the coffee shop near your area to pick it up.',
    sent_at: new Date(),
  },
  {
    sender_id: 5,
    receiver_id: 1,
    item_id: 3,
    content: 'Is this backpack blue with a laptop inside? I found one near the metro station and it looks important.',
    sent_at: new Date(),
  },
  {
    sender_id: 1,
    receiver_id: 5,
    item_id: 3,
    content: 'Yes! That’s mine. Thank you for keeping it safe. I can come by your place to get it whenever you’re free.',
    sent_at: new Date(),
  },
  {
    sender_id: 2,
    receiver_id: 3,
    item_id: 4,
    content: 'I found some keys near Nasr City. They have a small red keychain attached — is that yours?',
    sent_at: new Date(),
  },
  {
    sender_id: 3,
    receiver_id: 2,
    item_id: 4,
    content: 'Yes, that’s definitely mine. Thank you for finding them. I can meet you at the parking lot near the mall to collect them.',
    sent_at: new Date(),
  },
  {
    sender_id: 4,
    receiver_id: 5,
    item_id: 5,
    content: 'I believe this is the watch you lost. I picked it up from the bench near the park to keep it safe for you.',
    sent_at: new Date(),
  },
  {
    sender_id: 5,
    receiver_id: 4,
    item_id: 5,
    content: 'That’s amazing, thanks a lot! The strap and design match perfectly. I can come by to pick it up today.',
    sent_at: new Date(),
  },
   {
    sender_id: 6,
    receiver_id: 7,
    item_id: 6,
    content: 'Hey, I found a pair of sunglasses that looks like yours at the beach today. I kept them safe for you.',
    sent_at: new Date(),
  },
  {
    sender_id: 7,
    receiver_id: 6,
    item_id: 6,
    content: 'Oh, perfect! Thank you so much. Can I come by your place to pick them up?',
    sent_at: new Date(),
  },
  {
    sender_id: 8,
    receiver_id: 9,
    item_id: 7,
    content: 'I think I found your wallet near the bus station. It had a blue cover, right?',
    sent_at: new Date(),
  },
  {
    sender_id: 9,
    receiver_id: 8,
    item_id: 7,
    content: 'Yes! That’s mine. I really appreciate it. Where can we meet to collect it?',
    sent_at: new Date(),
  },
  {
    sender_id: 10,
    receiver_id: 11,
    item_id: 8,
    content: 'I found a handbag that matches the description from your post. It’s in good condition.',
    sent_at: new Date(),
  },
  {
    sender_id: 11,
    receiver_id: 10,
    item_id: 8,
    content: 'Amazing, thank you! Can we meet at the cafe near the metro station to get it?',
    sent_at: new Date(),
  },
  {
    sender_id: 12,
    receiver_id: 13,
    item_id: 9,
    content: 'I picked up a set of keys that might belong to you. They have a green keychain attached.',
    sent_at: new Date(),
  },
  {
    sender_id: 13,
    receiver_id: 12,
    item_id: 9,
    content: 'Yes! Those are mine. Thank you for keeping them safe. I can come collect them this afternoon.',
    sent_at: new Date(),
  },
  {
    sender_id: 14,
    receiver_id: 15,
    item_id: 10,
    content: 'I found your lost scarf near the market. It’s red with white stripes, correct?',
    sent_at: new Date(),
  },
  {
    sender_id: 15,
    receiver_id: 14,
    item_id: 10,
    content: 'Exactly! Thank you so much. I can come by the market entrance to pick it up.',
    sent_at: new Date(),
  },
  {
    sender_id: 16,
    receiver_id: 17,
    item_id: 11,
    content: 'I think this backpack belongs to you. Found it near the park entrance.',
    sent_at: new Date(),
  },
  {
    sender_id: 17,
    receiver_id: 16,
    item_id: 11,
    content: 'Yes! That’s definitely mine. Thanks for keeping it safe. When can I pick it up?',
    sent_at: new Date(),
  },
  {
    sender_id: 18,
    receiver_id: 19,
    item_id: 12,
    content: 'I found a pair of shoes matching your post. They are black with white stripes.',
    sent_at: new Date(),
  },
  {
    sender_id: 19,
    receiver_id: 18,
    item_id: 12,
    content: 'Perfect! That’s mine. I appreciate it. I can come by the main street to collect them.',
    sent_at: new Date(),
  },
  {
    sender_id: 20,
    receiver_id: 21,
    item_id: 13,
    content: 'I found your lost umbrella. It’s blue and has a wooden handle, right?',
    sent_at: new Date(),
  },
  {
    sender_id: 21,
    receiver_id: 20,
    item_id: 13,
    content: 'Yes, exactly! Thank you! I can meet you near the coffee shop to pick it up.',
    sent_at: new Date(),
  },
  {
    sender_id: 22,
    receiver_id: 23,
    item_id: 14,
    content: 'I picked up a jacket that might be yours. It’s dark green with a hood.',
    sent_at: new Date(),
  },
  {
    sender_id: 23,
    receiver_id: 22,
    item_id: 14,
    content: 'Yes, that’s mine. Thanks for keeping it safe. I can come by this evening to get it.',
    sent_at: new Date(),
  },
  {
    sender_id: 24,
    receiver_id: 25,
    item_id: 15,
    content: 'I found your wallet near the metro station entrance. It looks like the one in your post.',
    sent_at: new Date(),
  },
  {
    sender_id: 25,
    receiver_id: 24,
    item_id: 15,
    content: 'Awesome! That’s mine. Thank you so much! I can pick it up from your place anytime.',
    sent_at: new Date(),
  }      
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Messages', null, {});
  },
};
