'use strict';

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Addresses',
      [
        {
          name: 'Home',
          address: '12 Tahrir Street',
          city: 'Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11511',
          user_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '45 Ramses Road',
          city: 'Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11321',
          user_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '10 El Corniche',
          city: 'Alexandria',
          state: 'Alexandria',
          country: 'Egypt',
          postal_code: '21500',
          user_id: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '5 Mostafa Kamel St',
          city: 'Giza',
          state: 'Giza',
          country: 'Egypt',
          postal_code: '12611',
          user_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '22 El Rehab City',
          city: 'New Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11841',
          user_id: 5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '7 Saad Zaghloul St',
          city: 'Mansoura',
          state: 'Dakahlia',
          country: 'Egypt',
          postal_code: '35511',
          user_id: 6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '90 Gamal Abdel Nasser St',
          city: 'Suez',
          state: 'Suez',
          country: 'Egypt',
          postal_code: '43511',
          user_id: 7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '15 El Bahr St',
          city: 'Port Said',
          state: 'Port Said',
          country: 'Egypt',
          postal_code: '42511',
          user_id: 8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '33 El Nasr St',
          city: 'Ismailia',
          state: 'Ismailia',
          country: 'Egypt',
          postal_code: '41511',
          user_id: 9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '18 El Geish Road',
          city: 'Tanta',
          state: 'Gharbia',
          country: 'Egypt',
          postal_code: '31511',
          user_id: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Addresses', null, {});
  },
};
