'use strict';
/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [
      {
        name: 'Alice Johnson',
        age: 25,
        phone: '01011112222',
        email: 'alice@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Bob Smith',
        age: 30,
        phone: '01022223333',
        email: 'bob@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Carol Williams',
        age: 28,
        phone: '01033334444',
        email: 'carol@example.com',
        gender: 'female',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'David Brown',
        age: 35,
        phone: '01044445555',
        email: 'david@example.com',
        gender: 'male',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Eve Davis',
        age: 22,
        phone: '01055556666',
        email: 'eve@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Frank Miller',
        age: 40,
        phone: '01066667777',
        email: 'frank@example.com',
        gender: 'male',
        password: 'password123',
        role: 'owner',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Grace Wilson',
        age: 27,
        phone: '01077778888',
        email: 'grace@example.com',
        gender: 'female',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Henry Moore',
        age: 33,
        phone: '01088889999',
        email: 'henry@example.com',
        gender: 'male',
        password: 'password123',
        role: 'manager',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Isabella Taylor',
        age: 29,
        phone: '01099990000',
        email: 'isabella@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Jack Anderson',
        age: 31,
        phone: '01100001111',
        email: 'jack@example.com',
        gender: 'male',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Ahmed Ali',
        age: 26,
        phone: '01012121212',
        email: 'ahmed.ali@example.com',
        gender: 'male',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mohamed Hassan',
        age: 29,
        phone: '01023232323',
        email: 'mohamed.hassan@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Youssef Ibrahim',
        age: 24,
        phone: '01034343434',
        email: 'youssef.ibrahim@example.com',
        gender: 'male',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sara Mahmoud',
        age: 27,
        phone: '01045454545',
        email: 'sara.mahmoud@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mariam Adel',
        age: 23,
        phone: '01056565656',
        email: 'mariam.adel@example.com',
        gender: 'female',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Omar Khaled',
        age: 31,
        phone: '01067676767',
        email: 'omar.khaled@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Laila Mostafa',
        age: 28,
        phone: '01078787878',
        email: 'laila.mostafa@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Khaled Nour',
        age: 34,
        phone: '01089898989',
        email: 'khaled.nour@example.com',
        gender: 'male',
        password: 'password123',
        role: 'owner',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Hana Tarek',
        age: 22,
        phone: '01090909090',
        email: 'hana.tarek@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Tarek Samir',
        age: 36,
        phone: '01111112222',
        email: 'tarek.samir@example.com',
        gender: 'male',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },

      {
        name: 'Farah Yasser',
        age: 25,
        phone: '01122223333',
        email: 'farah.yasser@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mostafa Gamal',
        age: 30,
        phone: '01133334444',
        email: 'mostafa.gamal@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Nourhan Salah',
        age: 21,
        phone: '01144445555',
        email: 'nourhan.salah@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Aly Fathy',
        age: 32,
        phone: '01155556666',
        email: 'aly.fathy@example.com',
        gender: 'male',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Rana Ehab',
        age: 26,
        phone: '01166667777',
        email: 'rana.ehab@example.com',
        gender: 'female',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Amr Lotfy',
        age: 29,
        phone: '01177778888',
        email: 'amr.lotfy@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Yasmin Reda',
        age: 24,
        phone: '01188889999',
        email: 'yasmin.reda@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Ibrahim Adel',
        age: 35,
        phone: '01199990000',
        email: 'ibrahim.adel@example.com',
        gender: 'male',
        password: 'password123',
        role: 'owner',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Rita Fares',
        age: 23,
        phone: '01200001111',
        email: 'rita.fares@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mahmoud Zaki',
        age: 38,
        phone: '01211112222',
        email: 'mahmoud.zaki@example.com',
        gender: 'male',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Hadia Omar',
        age: 27,
        phone: '01222223333',
        email: 'hadia.omar@example.com',
        gender: 'female',
        password: 'password123',
        role: 'staff',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Adham Saber',
        age: 33,
        phone: '01233334444',
        email: 'adham.saber@example.com',
        gender: 'male',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Dana Khalil',
        age: 22,
        phone: '01244445555',
        email: 'dana.khalil@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Karim Saeed',
        age: 31,
        phone: '01255556666',
        email: 'karim.saeed@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Hager Nabil',
        age: 28,
        phone: '01266667777',
        email: 'hager.nabil@example.com',
        gender: 'female',
        password: 'password123',
        role: 'manager',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sameh Adel',
        age: 29,
        phone: '01277778888',
        email: 'sameh.adel@example.com',
        gender: 'male',
        password: 'password123',
        role: 'owner',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Yomna Fadel',
        age: 24,
        phone: '01288889999',
        email: 'yomna.fadel@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Sherif Magdy',
        age: 34,
        phone: '01299990000',
        email: 'sherif.magdy@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Nadine Younes',
        age: 22,
        phone: '01300001111',
        email: 'nadine.younes@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Bassel Helmy',
        age: 37,
        phone: '01311112222',
        email: 'bassel.helmy@example.com',
        gender: 'male',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },

      {
        name: 'Reem Tamer',
        age: 26,
        phone: '01322223333',
        email: 'reem.tamer@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Ziad Hossam',
        age: 30,
        phone: '01333334444',
        email: 'ziad.hossam@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Amina Fathy',
        age: 23,
        phone: '01344445555',
        email: 'amina.fathy@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Walid Sherif',
        age: 33,
        phone: '01355556666',
        email: 'walid.sherif@example.com',
        gender: 'male',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Lina Rashad',
        age: 25,
        phone: '01366667777',
        email: 'lina.rashad@example.com',
        gender: 'female',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Hamza Eid',
        age: 35,
        phone: '01377778888',
        email: 'hamza.eid@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Salma Badawy',
        age: 22,
        phone: '01388889999',
        email: 'salma.badawy@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Fares Montaser',
        age: 29,
        phone: '01399990000',
        email: 'fares.montaser@example.com',
        gender: 'male',
        password: 'password123',
        role: 'owner',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
        {
        name: 'Jana Mostafa',
        age: 24,
        phone: '01400001111',
        email: 'jana.mostafa@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Ayman Saber',
        age: 30,
        phone: '01411112222',
        email: 'ayman.saber@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },

      {
        name: 'Dalia Hassan',
        age: 26,
        phone: '01422223333',
        email: 'dalia.hassan@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Ashraf Fawzy',
        age: 34,
        phone: '01433334444',
        email: 'ashraf.fawzy@example.com',
        gender: 'male',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Nada Helal',
        age: 23,
        phone: '01444445555',
        email: 'nada.helal@example.com',
        gender: 'female',
        password: 'password123',
        role: 'staff',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Hussein Adel',
        age: 32,
        phone: '01455556666',
        email: 'hussein.adel@example.com',
        gender: 'male',
        password: 'password123',
        role: 'owner',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Mona Ibrahim',
        age: 28,
        phone: '01466667777',
        email: 'mona.ibrahim@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Tamer Lotfy',
        age: 31,
        phone: '01477778888',
        email: 'tamer.lotfy@example.com',
        gender: 'male',
        password: 'password123',
        role: 'staff',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Hala Nasser',
        age: 25,
        phone: '01488889999',
        email: 'hala.nasser@example.com',
        gender: 'female',
        password: 'password123',
        role: 'user',
        is_verified: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: 'Osama Gabr',
        age: 36,
        phone: '01499990000',
        email: 'osama.gabr@example.com',
        gender: 'male',
        password: 'password123',
        role: 'manager',
        is_verified: true,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  }
};
