'use strict';

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Addresses',
      [
        {
          name: 'Home',
          address: '12 Tahrir Street',
          city_id: 1,
          government_id: 1,
          postal_code: '11511',
          user_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '45 Ramses Road',
          city_id: 2,
          government_id: 1,
          postal_code: '11321',
          user_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '10 El Corniche',
          city_id: 58,
          government_id: 2,
          postal_code: '21500',
          user_id: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '5 Mostafa Kamel St',
          city_id: 59,
          government_id: 2,
          postal_code: '12611',
          user_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '22 El Rehab City',
          city_id: 3,
          government_id: 1,
          postal_code: '11841',
          user_id: 5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '7 Saad Zaghloul St',
          city_id: 137,
          government_id: 4,
          postal_code: '35511',
          user_id: 6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '90 Gamal Abdel Nasser St',
          city_id: 249,
          government_id: 14,
          postal_code: '43511',
          user_id: 7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '15 El Bahr St',
          city_id: 287,
          government_id: 18,
          postal_code: '42511',
          user_id: 8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '33 El Nasr St',
          city_id: 200,
          government_id: 9,
          postal_code: '41511',
          user_id: 9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '18 El Geish Road',
          city_id: 192,
          government_id: 8,
          postal_code: '31511',
          user_id: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '22 Thawra St',
          city_id: 306,
          government_id: 20,
          postal_code: '44511',
          user_id: 11,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '14 Port Fouad St',
          city_id: 295,
          government_id: 19,
          postal_code: '34511',
          user_id: 12,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '9 El Mahatta St',
          city_id: 266,
          government_id: 16,
          postal_code: '71511',
          user_id: 13,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '25 El Gamaa St',
          city_id: 157,
          government_id: 5,
          postal_code: '63511',
          user_id: 14,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '88 El Nahda St',
          city_id: 156,
          government_id: 5,
          postal_code: '61511',
          user_id: 15,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '4 El Horriya St',
          city_id: 143,
          government_id: 4,
          postal_code: '82511',
          user_id: 16,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '55 El Galaa St',
          city_id: 142,
          government_id: 4,
          postal_code: '85511',
          user_id: 17,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '301 Karnak Road',
          city_id: 141,
          government_id: 4,
          postal_code: '85955',
          user_id: 18,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '6 El Salam St',
          city_id: 140,
          government_id: 4,
          postal_code: '81511',
          user_id: 19,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '19 El Nile St',
          city_id: 139,
          government_id: 4,
          postal_code: '62511',
          user_id: 20,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '11 El Gomhouria St',
          city_id: 138,
          government_id: 4,
          postal_code: '83511',
          user_id: 21,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '66 El Nasr Road',
          city_id: 137,
          government_id: 4,
          postal_code: '84511',
          user_id: 22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '3 El Madina St',
          city_id: 100,
          government_id: 3,
          postal_code: '46619',
          user_id: 23,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '27 El Wehda St',
          city_id: 99,
          government_id: 3,
          postal_code: '45511',
          user_id: 24,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '50 International Rd',
          city_id: 98,
          government_id: 3,
          postal_code: '11828',
          user_id: 25,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '9 El Zahraa St',
          city_id: 97,
          government_id: 3,
          postal_code: '13511',
          user_id: 26,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '18 El Mostashfa St',
          city_id: 96,
          government_id: 3,
          postal_code: '33511',
          user_id: 27,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '41 El Masnaa St',
          city_id: 95,
          government_id: 3,
          postal_code: '13711',
          user_id: 28,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '2 El Zahraa Sq',
          city_id: 94,
          government_id: 3,
          postal_code: '32511',
          user_id: 29,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '17 El Geish St',
          city_id: 93,
          government_id: 3,
          postal_code: '32911',
          user_id: 30,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '30 El Bahr St',
          city_id: 27,
          government_id: 1,
          postal_code: '61611',
          user_id: 31,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '55 Palm District',
          city_id: 2,
          government_id: 1,
          postal_code: '61919',
          user_id: 32,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '7 El Fardoos St',
          city_id: 27,
          government_id: 1,
          postal_code: '61711',
          user_id: 33,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '44 El Gomhouria St',
          city_id: 32,
          government_id: 1,
          postal_code: '61811',
          user_id: 34,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '15 El Wadi St',
          city_id: 33,
          government_id: 1,
          postal_code: '71611',
          user_id: 35,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Office',
          address: '50 El Sadat Rd',
          city_id: 30,
          government_id: 1,
          postal_code: '11865',
          user_id: 36,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '77 6th District',
          city_id: 24,
          government_id: 1,
          postal_code: '12573',
          user_id: 37,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '100 El Wahat St',
          city_id: 29,
          government_id: 1,
          postal_code: '12577',
          user_id: 38,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Villa',
          address: '33 El Lotus Rd',
          city_id: 27,
          government_id: 1,
          postal_code: '11843',
          user_id: 39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '15 El Andalus',
          city_id: 20,
          government_id: 1,
          postal_code: '11876',
          user_id: 40,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Office',
          address: '8 El Sarayat St',
          city_id: 62,
          government_id: 2,
          postal_code: '11795',
          user_id: 41,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '20 El Mashtal St',
          city_id: 60,
          government_id: 2,
          postal_code: '11431',
          user_id: 42,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '14 El Horreya Ave',
          city_id: 59,
          government_id: 2,
          postal_code: '21614',
          user_id: 43,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '60 Stanley Bridge Rd',
          city_id: 58,
          government_id: 2,
          postal_code: '21532',
          user_id: 44,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '10 El Galaa St',
          city_id: 160,
          government_id: 5,
          postal_code: '41515',
          user_id: 45,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '33 El Bahr Ave',
          city_id: 161,
          government_id: 5,
          postal_code: '43512',
          user_id: 46,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Office',
          address: '22 El Mostashfa St',
          city_id: 162,
          government_id: 5,
          postal_code: '35514',
          user_id: 47,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '5 El Embassy St',
          city_id: 164,
          government_id: 6,
          postal_code: '31512',
          user_id: 48,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Apartment',
          address: '12 El Watan St',
          city_id: 165,
          government_id: 6,
          postal_code: '42512',
          user_id: 49,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '4 El Masry St',
          city_id: 166,
          government_id: 6,
          postal_code: '42526',
          user_id: 50,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '18 El Waha District',
          city_id: 20,
          government_id: 1,
          postal_code: '11371',
          user_id: 51,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '400 Mirage Area',
          city_id: 17,
          government_id: 1,
          postal_code: '11885',
          user_id: 52,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '40 El Mahrousa St',
          city_id: 167,
          government_id: 6,
          postal_code: '12654',
          user_id: 53,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '12 El Haram St',
          city_id: 169,
          government_id: 6,
          postal_code: '12556',
          user_id: 54,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '3 El Khazindar St',
          city_id: 15,
          government_id: 1,
          postal_code: '11629',
          user_id: 55,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '100 El Azhar St',
          city_id: 12,
          government_id: 1,
          postal_code: '11675',
          user_id: 56,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Apartment',
          address: '22 El Fostat Rd',
          city_id: 3,
          government_id: 1,
          postal_code: '11521',
          user_id: 57,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '11 El Zahraa Rd',
          city_id: 5,
          government_id: 1,
          postal_code: '11757',
          user_id: 58,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Office',
          address: '8 El Thawra Tunnel',
          city_id: 6,
          government_id: 1,
          postal_code: '11381',
          user_id: 39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '70 El Makram Ebeid',
          city_id: 10,
          government_id: 1,
          postal_code: '11391',
          user_id: 10,
          created_at: new Date(),
          updated_at: new Date(),
        }
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Addresses', null, {});
  },
};
