'use strict';

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Items',
      [
        {
          title: 'Lost Wallet',
          location: 'Downtown Cairo',
          type: 'lost',
          description: 'Black leather wallet with several cards',
          user_id: 1,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Mobile Phone',
          location: 'Alexandria Corniche',
          type: 'found',
          description: 'Samsung phone found near the beach',
          user_id: 2,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Backpack',
          location: 'Giza Metro Station',
          type: 'lost',
          description: 'Blue backpack with laptop inside',
          user_id: 3,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Keys',
          location: 'Nasr City',
          type: 'found',
          description: 'House keys with red keychain',
          user_id: 4,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Watch',
          location: 'Mall of Egypt',
          type: 'lost',
          description: 'Silver wrist watch, brand unknown',
          user_id: 5,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Headphones',
          location: 'Cairo University',
          type: 'found',
          description: 'Wireless black headphones',
          user_id: 1,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost ID Card',
          location: 'Heliopolis',
          type: 'lost',
          description: 'National ID card issued in Cairo',
          user_id: 2,
          item_category_id: 6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Sunglasses',
          location: 'New Cairo',
          type: 'found',
          description: 'Brown sunglasses found in a cafe',
          user_id: 3,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Jacket',
          location: 'October City',
          type: 'lost',
          description: 'Black winter jacket size L',
          user_id: 4,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Power Bank',
          location: 'Ramses Station',
          type: 'found',
          description: 'White power bank, 20000mAh',
          user_id: 5,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
         {
    title: 'Lost Wallet',
    location: 'Zamalek',
    type: 'lost',
    description: 'Brown leather wallet with multiple cards and some cash',
    user_id: 6,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Backpack',
    location: 'Nasr City Metro Station',
    type: 'found',
    description: 'Grey backpack with school books inside',
    user_id: 7,
    item_category_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Mobile Phone',
    location: 'Helwan',
    type: 'lost',
    description: 'iPhone 13, black color, no case',
    user_id: 8,
    item_category_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Wallet',
    location: 'Downtown Alexandria',
    type: 'found',
    description: 'Black wallet with a few cards, no cash',
    user_id: 9,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Keys',
    location: 'Maadi',
    type: 'lost',
    description: 'House keys with blue keychain',
    user_id: 10,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Watch',
    location: 'Heliopolis',
    type: 'found',
    description: 'Silver wrist watch with leather strap',
    user_id: 6,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Headphones',
    location: 'Cairo University',
    type: 'lost',
    description: 'Wireless black headphones with noise cancellation',
    user_id: 7,
    item_category_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found ID Card',
    location: 'Giza',
    type: 'found',
    description: 'National ID card issued in Cairo',
    user_id: 8,
    item_category_id: 6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Sunglasses',
    location: 'New Cairo',
    type: 'lost',
    description: 'Brown aviator sunglasses with metal frame',
    user_id: 9,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Jacket',
    location: 'October City',
    type: 'found',
    description: 'Black winter jacket size M, lightly worn',
    user_id: 10,
    item_category_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Power Bank',
    location: 'Ramses Station',
    type: 'lost',
    description: 'White power bank, 20000mAh capacity',
    user_id: 6,
    item_category_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Backpack',
    location: 'Alexandria Corniche',
    type: 'found',
    description: 'Red backpack with school notebooks',
    user_id: 7,
    item_category_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Wallet',
    location: 'Downtown Cairo',
    type: 'lost',
    description: 'Small black wallet with coins and a few credit cards',
    user_id: 8,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Mobile Phone',
    location: 'Giza Metro Station',
    type: 'found',
    description: 'Samsung Galaxy A12, black color',
    user_id: 9,
    item_category_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Keys',
    location: 'Nasr City',
    type: 'lost',
    description: 'Car keys with a red keychain and remote',
    user_id: 10,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Watch',
    location: 'Maadi',
    type: 'found',
    description: 'Gold-colored wrist watch, brand unknown',
    user_id: 6,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Headphones',
    location: 'Cairo University',
    type: 'lost',
    description: 'Over-ear black headphones, wireless',
    user_id: 7,
    item_category_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Sunglasses',
    location: 'Zamalek',
    type: 'found',
    description: 'Round brown sunglasses, lightly scratched',
    user_id: 8,
    item_category_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Lost Jacket',
    location: 'New Cairo',
    type: 'lost',
    description: 'Blue denim jacket, size L',
    user_id: 9,
    item_category_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: 'Found Power Bank',
    location: 'Ramses Station',
    type: 'found',
    description: 'Black power bank, 10000mAh',
    user_id: 10,
    item_category_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  }      
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Items', null, {});
  },
};
