'use strict';

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Items',
      [
        {
          title: 'Lost Wallet',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Black leather wallet with several cards',
          user_id: 1,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Mobile Phone',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Samsung phone found near the beach',
          user_id: 2,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Backpack',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Blue backpack with laptop inside',
          user_id: 3,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Keys',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'House keys with red keychain',
          user_id: 4,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Watch',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Silver wrist watch, brand unknown',
          user_id: 5,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Headphones',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Wireless black headphones',
          user_id: 1,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost ID Card',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'National ID card issued in Cairo',
          user_id: 2,
          item_category_id: 6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Sunglasses',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Brown sunglasses found in a cafe',
          user_id: 3,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Jacket',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Black winter jacket size L',
          user_id: 4,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Power Bank',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'White power bank, 20000mAh',
          user_id: 5,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Wallet',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Brown leather wallet with multiple cards and some cash',
          user_id: 6,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Backpack',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Grey backpack with school books inside',
          user_id: 7,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Mobile Phone',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'iPhone 13, black color, no case',
          user_id: 8,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Wallet',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Black wallet with a few cards, no cash',
          user_id: 9,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Keys',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'House keys with blue keychain',
          user_id: 10,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Watch',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Silver wrist watch with leather strap',
          user_id: 6,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Headphones',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Wireless black headphones with noise cancellation',
          user_id: 7,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found ID Card',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'National ID card issued in Cairo',
          user_id: 8,
          item_category_id: 6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Sunglasses',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Brown aviator sunglasses with metal frame',
          user_id: 9,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Jacket',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Black winter jacket size M, lightly worn',
          user_id: 10,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Power Bank',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'White power bank, 20000mAh capacity',
          user_id: 6,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Backpack',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Red backpack with school notebooks',
          user_id: 7,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Wallet',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Small black wallet with coins and a few credit cards',
          user_id: 8,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Mobile Phone',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Samsung Galaxy A12, black color',
          user_id: 9,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Keys',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Car keys with a red keychain and remote',
          user_id: 10,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Watch',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Gold-colored wrist watch, brand unknown',
          user_id: 6,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Headphones',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Over-ear black headphones, wireless',
          user_id: 7,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Sunglasses',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Round brown sunglasses, lightly scratched',
          user_id: 8,
          item_category_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Lost Jacket',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'lost',
          description: 'Blue denim jacket, size L',
          user_id: 9,
          item_category_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Found Power Bank',
          government: 'Cairo',
          city: 'Shobra',
          place: 'cafe',
          date: '2025-01-08',
          type: 'found',
          description: 'Black power bank, 10000mAh',
          user_id: 10,
          item_category_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        }      
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Items', null, {});
  },
};
