'use strict';

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Addresses',
      [
        {
          name: 'Home',
          address: '12 Tahrir Street',
          city: 'Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11511',
          user_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '45 Ramses Road',
          city: 'Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11321',
          user_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '10 El Corniche',
          city: 'Alexandria',
          state: 'Alexandria',
          country: 'Egypt',
          postal_code: '21500',
          user_id: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '5 Mostafa Kamel St',
          city: 'Giza',
          state: 'Giza',
          country: 'Egypt',
          postal_code: '12611',
          user_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '22 El Rehab City',
          city: 'New Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11841',
          user_id: 5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '7 Saad Zaghloul St',
          city: 'Mansoura',
          state: 'Dakahlia',
          country: 'Egypt',
          postal_code: '35511',
          user_id: 6,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '90 Gamal Abdel Nasser St',
          city: 'Suez',
          state: 'Suez',
          country: 'Egypt',
          postal_code: '43511',
          user_id: 7,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '15 El Bahr St',
          city: 'Port Said',
          state: 'Port Said',
          country: 'Egypt',
          postal_code: '42511',
          user_id: 8,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '33 El Nasr St',
          city: 'Ismailia',
          state: 'Ismailia',
          country: 'Egypt',
          postal_code: '41511',
          user_id: 9,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '18 El Geish Road',
          city: 'Tanta',
          state: 'Gharbia',
          country: 'Egypt',
          postal_code: '31511',
          user_id: 10,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '22 Thawra St',
          city: 'Zagazig',
          state: 'Sharqia',
          country: 'Egypt',
          postal_code: '44511',
          user_id: 11,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '14 Port Fouad St',
          city: 'Damietta',
          state: 'Damietta',
          country: 'Egypt',
          postal_code: '34511',
          user_id: 12,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '9 El Mahatta St',
          city: 'Asyut',
          state: 'Asyut',
          country: 'Egypt',
          postal_code: '71511',
          user_id: 13,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '25 El Gamaa St',
          city: 'Fayoum',
          state: 'Fayoum',
          country: 'Egypt',
          postal_code: '63511',
          user_id: 14,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '88 El Nahda St',
          city: 'Minya',
          state: 'Minya',
          country: 'Egypt',
          postal_code: '61511',
          user_id: 15,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '4 El Horriya St',
          city: 'Sohag',
          state: 'Sohag',
          country: 'Egypt',
          postal_code: '82511',
          user_id: 16,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '55 El Galaa St',
          city: 'Luxor',
          state: 'Luxor',
          country: 'Egypt',
          postal_code: '85511',
          user_id: 17,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '301 Karnak Road',
          city: 'Luxor',
          state: 'Luxor',
          country: 'Egypt',
          postal_code: '85955',
          user_id: 18,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '6 El Salam St',
          city: 'Aswan',
          state: 'Aswan',
          country: 'Egypt',
          postal_code: '81511',
          user_id: 19,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '19 El Nile St',
          city: 'Beni Suef',
          state: 'Beni Suef',
          country: 'Egypt',
          postal_code: '62511',
          user_id: 20,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '11 El Gomhouria St',
          city: 'Qena',
          state: 'Qena',
          country: 'Egypt',
          postal_code: '83511',
          user_id: 21,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '66 El Nasr Road',
          city: 'Hurghada',
          state: 'Red Sea',
          country: 'Egypt',
          postal_code: '84511',
          user_id: 22,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '3 El Madina St',
          city: 'Sharm El Sheikh',
          state: 'South Sinai',
          country: 'Egypt',
          postal_code: '46619',
          user_id: 23,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '27 El Wehda St',
          city: 'Arish',
          state: 'North Sinai',
          country: 'Egypt',
          postal_code: '45511',
          user_id: 24,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '50 International Rd',
          city: 'Obour',
          state: 'Qalyubia',
          country: 'Egypt',
          postal_code: '11828',
          user_id: 25,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '9 El Zahraa St',
          city: 'Banha',
          state: 'Qalyubia',
          country: 'Egypt',
          postal_code: '13511',
          user_id: 26,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '18 El Mostashfa St',
          city: 'Kafr El Sheikh',
          state: 'Kafr El Sheikh',
          country: 'Egypt',
          postal_code: '33511',
          user_id: 27,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '41 El Masnaa St',
          city: 'Qalyub',
          state: 'Qalyubia',
          country: 'Egypt',
          postal_code: '13711',
          user_id: 28,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '2 El Zahraa Sq',
          city: 'Shibin El Kom',
          state: 'Monufia',
          country: 'Egypt',
          postal_code: '32511',
          user_id: 29,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '17 El Geish St',
          city: 'Menouf',
          state: 'Monufia',
          country: 'Egypt',
          postal_code: '32911',
          user_id: 30,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '30 El Bahr St',
          city: 'Beni Mazar',
          state: 'Minya',
          country: 'Egypt',
          postal_code: '61611',
          user_id: 31,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '55 Palm District',
          city: 'New Minya',
          state: 'Minya',
          country: 'Egypt',
          postal_code: '61919',
          user_id: 32,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '7 El Fardoos St',
          city: 'Mallawi',
          state: 'Minya',
          country: 'Egypt',
          postal_code: '61711',
          user_id: 33,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '44 El Gomhouria St',
          city: 'Samalut',
          state: 'Minya',
          country: 'Egypt',
          postal_code: '61811',
          user_id: 34,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '15 El Wadi St',
          city: 'Abnub',
          state: 'Asyut',
          country: 'Egypt',
          postal_code: '71611',
          user_id: 35,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Office',
          address: '50 El Sadat Rd',
          city: 'New Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11865',
          user_id: 36,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '77 6th District',
          city: 'October',
          state: 'Giza',
          country: 'Egypt',
          postal_code: '12573',
          user_id: 37,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '100 El Wahat St',
          city: 'October',
          state: 'Giza',
          country: 'Egypt',
          postal_code: '12577',
          user_id: 38,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Villa',
          address: '33 El Lotus Rd',
          city: 'New Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11843',
          user_id: 39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '15 El Andalus',
          city: 'New Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11876',
          user_id: 40,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Office',
          address: '8 El Sarayat St',
          city: 'Helwan',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11795',
          user_id: 41,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '20 El Mashtal St',
          city: 'Maadi',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11431',
          user_id: 42,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '14 El Horreya Ave',
          city: 'Alexandria',
          state: 'Alexandria',
          country: 'Egypt',
          postal_code: '21614',
          user_id: 43,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '60 Stanley Bridge Rd',
          city: 'Alexandria',
          state: 'Alexandria',
          country: 'Egypt',
          postal_code: '21532',
          user_id: 44,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '10 El Galaa St',
          city: 'Ismailia',
          state: 'Ismailia',
          country: 'Egypt',
          postal_code: '41515',
          user_id: 45,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '33 El Bahr Ave',
          city: 'Suez',
          state: 'Suez',
          country: 'Egypt',
          postal_code: '43512',
          user_id: 46,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Office',
          address: '22 El Mostashfa St',
          city: 'Mansoura',
          state: 'Dakahlia',
          country: 'Egypt',
          postal_code: '35514',
          user_id: 47,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '5 El Embassy St',
          city: 'Tanta',
          state: 'Gharbia',
          country: 'Egypt',
          postal_code: '31512',
          user_id: 48,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Apartment',
          address: '12 El Watan St',
          city: 'Port Said',
          state: 'Port Said',
          country: 'Egypt',
          postal_code: '42512',
          user_id: 49,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '4 El Masry St',
          city: 'Port Fouad',
          state: 'Port Said',
          country: 'Egypt',
          postal_code: '42526',
          user_id: 50,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '18 El Waha District',
          city: 'Nasr City',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11371',
          user_id: 51,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Villa',
          address: '400 Mirage Area',
          city: 'New Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11885',
          user_id: 52,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '40 El Mahrousa St',
          city: 'Giza',
          state: 'Giza',
          country: 'Egypt',
          postal_code: '12654',
          user_id: 53,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Apartment',
          address: '12 El Haram St',
          city: 'Giza',
          state: 'Giza',
          country: 'Egypt',
          postal_code: '12556',
          user_id: 54,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Home',
          address: '3 El Khazindar St',
          city: 'Shubra',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11629',
          user_id: 55,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Office',
          address: '100 El Azhar St',
          city: 'Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11675',
          user_id: 56,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Apartment',
          address: '22 El Fostat Rd',
          city: 'Old Cairo',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11521',
          user_id: 57,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '11 El Zahraa Rd',
          city: 'Heliopolis',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11757',
          user_id: 58,
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          name: 'Office',
          address: '8 El Thawra Tunnel',
          city: 'Nasr City',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11381',
          user_id: 39,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Home',
          address: '70 El Makram Ebeid',
          city: 'Nasr City',
          state: 'Cairo',
          country: 'Egypt',
          postal_code: '11391',
          user_id: 10,
          created_at: new Date(),
          updated_at: new Date(),
        }
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Addresses', null, {});
  },
};
